sonar.projectKey=imagenes_service
sonar.projectName=imagenes_service
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/vendor/**, **/test/**, **/build/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.sourceEncoding=UTF-8
