appname = ${APP_NAME||imagenes_service}
httpport = ${APP_PORT||8000}
runmode = ${RUNMODE||prod}
debug = ${DEBUG||false}

# Amazon Rekognition para validación de rostros
aws_region = ${AWS_REGION}
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
rekognition_endpoint_url = ${REKOGNITION_ENDPOINT_URL||}
rekognition_min_face_confidence = ${REKOGNITION_MIN_FACE_CONFIDENCE||90}
rekognition_max_image_size_mb = ${REKOGNITION_MAX_IMAGE_SIZE_MB||5}

copyrequestbody = true
